wandb_version: 1

learning_rate:
  desc: null
  value: 0.002
architecture:
  desc: null
  value: my_model
dataset:
  desc: null
  value: my_dataset
epochs:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713006678.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.4
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
